### ISSUE TITLE
 Cannot read property 'split' of null

### ISSUE THREAD

**Issue by eonchen** [MUYIio/hexo-themes-matery#8]
FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
TypeError: Cannot read property 'split' of null
    at parseRepo (D:\software\blog\ces\eonchen\node_modules\hexo-deployer-git\lib\parse_config.js:7:20)
    at module.exports (D:\software\blog\ces\eonchen\node_modules\hexo-deployer-git\lib\parse_config.js:44:17)
    at D:\software\blog\ces\eonchen\node_modules\hexo-deployer-git\lib\deployer.js:152:12
    at tryCatcher (D:\software\blog\ces\eonchen\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\software\blog\ces\eonchen\node_modules\bluebird\js\release\promise.js:517:31)
    at Promise._settlePromise (D:\software\blog\ces\eonchen\node_modules\bluebird\js\release\promise.js:574:18)
    at Promise._settlePromise0 (D:\software\blog\ces\eonchen\node_modules\bluebird\js\release\promise.js:619:10)
    at Promise._settlePromises (D:\software\blog\ces\eonchen\node_modules\bluebird\js\release\promise.js:699:18)
    at Promise._fulfill (D:\software\blog\ces\eonchen\node_modules\bluebird\js\release\promise.js:643:18)
    at Promise._resolveCallback (D:\software\blog\ces\eonchen\node_modules\bluebird\js\release\promise.js:437:57)
    at Promise._settlePromiseFromHandler (D:\software\blog\ces\eonchen\node_modules\bluebird\js\release\promise.js:529:17)
    at Promise._settlePromise (D:\software\blog\ces\eonchen\node_modules\bluebird\js\release\promise.js:574:18)
    at Promise._settlePromise0 (D:\software\blog\ces\eonchen\node_modules\bluebird\js\release\promise.js:619:10)
    at Promise._settlePromises (D:\software\blog\ces\eonchen\node_modules\bluebird\js\release\promise.js:699:18)
    at Promise._fulfill (D:\software\blog\ces\eonchen\node_modules\bluebird\js\release\promise.js:643:18)
    at Promise._resolveCallback (D:\software\blog\ces\eonchen\node_modules\bluebird\js\release\promise.js:437:57)
    at ReductionPromiseArray._resolve (D:\software\blog\ces\eonchen\node_modules\bluebird\js\release\reduce.js:61:19)
    at Promise.completed [as _fulfillmentHandler0] (D:\software\blog\ces\eonchen\node_modules\bluebird\js\release\reduce.js:122:15)
    at Promise._settlePromise (D:\software\blog\ces\eonchen\node_modules\bluebird\js\release\promise.js:571:21)
    at Promise._settlePromise0 (D:\software\blog\ces\eonchen\node_modules\bluebird\js\release\promise.js:619:10)
    at Promise._settlePromises (D:\software\blog\ces\eonchen\node_modules\bluebird\js\release\promise.js:699:18)
    at _drainQueueStep (D:\software\blog\ces\eonchen\node_modules\bluebird\js\release\async.js:138:12)

**Comment by MUYIio** [comment]
node版本过高，切换至14.0以下即可解决！

**Comment by MUYIio** [comment]
close
