### ISSUE TITLE
The "mode" argument must be integer

### ISSUE THREAD

**Issue by zyl1336110861** [MUYIio/hexo-themes-matery#9]
Thanks very much for your sharing! When I used the "hexo d" instruction, I got  the following error:
`
$ hexo d

INFO  Deploying: git
INFO  Clearing .deploy_git folder...
INFO  Copying files from public folder...
FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
TypeError [ERR_INVALID_ARG_TYPE]: The "mode" argument must be integer. Received an instance of Object
    at copyFile (node:fs:2774:10)
    at tryCatcher (E:\zylBlog2\node_modules\bluebird\js\release\util.js:16:23)
    at ret (eval at makeNodePromisifiedEval (C:\Users\admin\AppData\Roaming\npm\node_modules\hexo-cli\node_modules\bluebird\js\release\promisify.js:184:12), <anonymous>:13:39)
    at E:\zylBlog2\node_modules\hexo-fs\lib\fs.js:144:39
    at tryCatcher (E:\zylBlog2\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\zylBlog2\node_modules\bluebird\js\release\promise.js:517:31)
    at Promise._settlePromise (E:\zylBlog2\node_modules\bluebird\js\release\promise.js:574:18)
    at Promise._settlePromise0 (E:\zylBlog2\node_modules\bluebird\js\release\promise.js:619:10)
    at Promise._settlePromises (E:\zylBlog2\node_modules\bluebird\js\release\promise.js:699:18)
    at Promise._fulfill (E:\zylBlog2\node_modules\bluebird\js\release\promise.js:643:18)
    at Promise._resolveCallback (E:\zylBlog2\node_modules\bluebird\js\release\promise.js:437:57)
    at Promise._settlePromiseFromHandler (E:\zylBlog2\node_modules\bluebird\js\release\promise.js:529:17)
    at Promise._settlePromise (E:\zylBlog2\node_modules\bluebird\js\release\promise.js:574:18)
    at Promise._settlePromise0 (E:\zylBlog2\node_modules\bluebird\js\release\promise.js:619:10)
    at Promise._settlePromises (E:\zylBlog2\node_modules\bluebird\js\release\promise.js:699:18)
    at Promise._fulfill (E:\zylBlog2\node_modules\bluebird\js\release\promise.js:643:18)
    at Promise._resolveCallback (E:\zylBlog2\node_modules\bluebird\js\release\promise.js:437:57)
    at Promise._settlePromiseFromHandler (E:\zylBlog2\node_modules\bluebird\js\release\promise.js:529:17)
    at Promise._settlePromise (E:\zylBlog2\node_modules\bluebird\js\release\promise.js:574:18)
    at Promise._settlePromise0 (E:\zylBlog2\node_modules\bluebird\js\release\promise.js:619:10)
    at Promise._settlePromises (E:\zylBlog2\node_modules\bluebird\js\release\promise.js:699:18)
    at Promise._fulfill (E:\zylBlog2\node_modules\bluebird\js\release\promise.js:643:18)
`
How can I solve this problem?

**Comment by MUYIio** [comment]
node版本
